language: python
python:
  - "2.6"
  - "2.7"
  # - "3.4"

branches:
  only:
    - master
    - develop
    - /^release-.*$/

before_install:
  # Install blas/lapack
  - sudo apt-get update -qq
  - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-base-dev gfortran
  # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pytest dateutil pandas scikit-learn sympy
  # - pip install -r requirements.txt
  - pip install lmfit
  - python setup.py install

# command to run tests
script: py.test test/

